Get things working as independent tool

diff --git a/src/collect-dependencies b/src/collect-dependencies
--- a/src/collect-dependencies
+++ b/src/collect-dependencies
@@ -4,18 +4,22 @@ ALLE_PKG_JSON_PATH="./package.json"
 ALLE_PKG_JSON_LKG_PATH="/tmp/package.lkg.json"
 ALLE_PKG_JSON_UPDATED_PATH="/tmp/package.updated.json"
 
-cleanup() {
-  if [ -e "$ALLE_PKG_JSON_LKG_PATH" ]; then
-    rm "$ALLE_PKG_JSON_LKG_PATH"
-  fi
-  if [ -e "$ALLE_PKG_JSON_UPDATED_PATH" ]; then
-    rm "$ALLE_PKG_JSON_UPDATED_PATH"
-  fi
+# see https://stackoverflow.com/a/246128/5354298
+get_script_dir() { echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; }
+SCRIPT_DIR=$(get_script_dir)
+START_DIR=$(pwd)
+on_error() {
+  # Restoring last-know-good package.json
+  cp "$ALLE_PKG_JSON_LKG_PATH" "$ALLE_PKG_JSON_PATH"
 }
-
+cleanup_complete=0
+cleanup() {
+  echo 'Cleaning up...'
+  cd "$START_DIR" || return
+  cleanup_complete=1
+}
 # Based on http://linuxcommand.org/lc3_wss0140.php
 # and https://codeinthehole.com/tips/bash-error-reporting/
-PROGNAME=$(basename $0)
 error_exit() {
   #	----------------------------------------------------------------
   #	Function for exit due to fatal program error
@@ -23,25 +27,30 @@ error_exit() {
   #			string containing descriptive error message
   #	----------------------------------------------------------------
 
-  # Restoring last-know-good package.json
-  cp "$ALLE_PKG_JSON_LKG_PATH" "$ALLE_PKG_JSON_PATH"
+  on_error
 
-  #echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  read -r line file <<<"$(caller)"
+  echo "" 1>&2
+  echo "ERROR: file $file, line $line" 1>&2
   if [ ! "$1" ]; then
-    echo "${PROGNAME}: Unknown Error" 1>&2
-    read line file <<<$(caller)
-    echo "An error occurred in line $line of file $file:" 1>&2
-    sed "${line}q;d" "$file" 1>&2
+    sed "${line}q;d" "$SCRIPT_DIR/$file" 1>&2
   else
-    echo "${PROGNAME}: $1" 1>&2
+    echo "${1:-"Unknown Error"}" 1>&2
   fi
+  echo "" 1>&2
 
-  cleanup
+  # TODO: should error_exit call cleanup?
+  #       The EXIT trap already calls cleanup, so
+  #       calling it here means calling it twice.
+  if [ ! $cleanup_complete ]; then
+    cleanup
+  fi
   exit 1
 }
-
 trap error_exit ERR
 trap cleanup EXIT INT QUIT TERM
+shopt -s globstar
+shopt -s extglob
 
 if [ ! -e "$ALLE_PKG_JSON_PATH" ]; then
   echo "Missing alle top-level package.json"
@@ -52,7 +61,7 @@ fi
 
 cp "$ALLE_PKG_JSON_PATH" "$ALLE_PKG_JSON_LKG_PATH"
 
-package_json_paths=$(ls -1 packages/node_modules/\@*/*/package.json packages/node_modules/*/package.json)
+package_json_paths=$(ls -1 packages/node_modules/!(available)/**/package.json)
 
 names=$(cat $package_json_paths |
   jq --slurp 'map(.name)')
diff --git a/src/update b/src/update
--- a/src/update
+++ b/src/update
@@ -3,10 +3,14 @@
 # see https://stackoverflow.com/a/246128/5354298
 get_script_dir() { echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; }
 SCRIPT_DIR=$(get_script_dir)
+START_DIR=$(pwd)
+on_error() {
+  true
+}
 cleanup_complete=0
 cleanup() {
   echo 'Cleaning up...'
-  cd "$SCRIPT_DIR" || return
+  cd "$START_DIR" || return
   cleanup_complete=1
 }
 # Based on http://linuxcommand.org/lc3_wss0140.php
@@ -18,11 +22,14 @@ error_exit() {
   #			string containing descriptive error message
   #	----------------------------------------------------------------
 
+  on_error
+
   read -r line file <<<"$(caller)"
   echo "" 1>&2
   echo "ERROR: file $file, line $line" 1>&2
   if [ ! "$1" ]; then
-    sed "${line}q;d" "$SCRIPT_DIR/$file" 1>&2
+    #sed "${line}q;d" "$SCRIPT_DIR/$file" 1>&2
+    sed "${line}q;d" "$file" 1>&2
   else
     echo "${1:-"Unknown Error"}" 1>&2
   fi
@@ -38,6 +45,8 @@ error_exit() {
 }
 trap error_exit ERR
 trap cleanup EXIT INT QUIT TERM
+shopt -s globstar
+shopt -s extglob
 
 # PACKAGE_LOCK_PATH="./package-lock.json"
 
@@ -52,9 +61,9 @@ npm update
 #fi
 npm audit fix
 
-package_json_paths=$(ls -1 packages/node_modules/\@*/*/package.json packages/node_modules/*/package.json)
+package_json_paths=$(ls -1 packages/node_modules/!(available)/**/package.json)
 
-names=$(jq -r '.[] | .name' local-packages.json)
+names=$(jq -sr '.[] | .name' local-packages.json)
 
 package_json_path="./package.json"
 lockfile_path="./package-lock.json"
@@ -72,7 +81,7 @@ third_party_dependencies=$(jq '(.dependencies // {})' $package_json_path)
 #	  cp ./package.json ./package-lkg.json
 #	fi
 #	git checkout package.json
-#	cd "$SCRIPT_DIR" || error_exit "Error: 'cd \"$SCRIPT_DIR\"' failed."
+#	cd "$START_DIR" || error_exit "Error: 'cd \"$START_DIR\"' failed."
 #done
 
 # alle_dependencies: all packages, both local and third-party, for this project.
@@ -101,7 +110,7 @@ END
 )
 
 for pkg in $names; do
-  cd "$SCRIPT_DIR" || error_exit "Error: 'cd \"$SCRIPT_DIR\"' failed."
+  cd "$START_DIR" || error_exit "Error: 'cd \"$START_DIR\"' failed."
 
   echo "**********************************"
   echo "* $pkg"
@@ -183,7 +192,7 @@ for pkg in $names; do
   npm run --silent test || error_exit \
     "Error: 'npm run --silent test' failed for $pkg. Remove '--silent' to debug."
 
-  cd "$SCRIPT_DIR" || error_exit "Error: 'cd \"$SCRIPT_DIR\"' failed."
+  cd "$START_DIR" || error_exit "Error: 'cd \"$START_DIR\"' failed."
 done
 
 if ! npm audit; then
